baseurl: "openfresh.github.io/a11y-guidelines"
title: "FRESH! Accessibility Guidelines"
footnotereturnlinkcontents: "â†©"
contentdir: "content"
layoutdir: "layouts"
staticdir: "static"
publishdir: "public"
uglyUrls: false
metaDataFormat: "yaml"
permalinks:
  post: "/:title"
